ProduitBundle/Entity/Produit.php
<?php


namespace ProduitBundle\Entity;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 */
class Produit
{

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
 private  $IdProduit;
    /**
     * @ORM\Column(type="string",length=255)
     *
     */
 private  $NameProduit;
    /**
     * @ORM\Column(type="string",length=255)
     *
     */
 private $TypeProduit;
    /**
     * @ORM\Column(type="integer")
     *
     */
 private $QuantityProduit;
    /**
     * @ORM\Column(type="integer")
     *
     */
 private $PriceProduit;
    /**
     * @ORM\Column(type="string",length=255)
     * @var string
     */
 private $PictureProduit;
    /**
     * @ORM\Column(type="string",length=255)
     *
     */
 private $DescriptionProduit;

    /**
     * @ORM\Column(type="datetime")
     *
     */
    private $DateProduit;
    /**
     * @ORM\ManyToOne(targetEntity="CategoryProduit")
     * @ORM\JoinColumn(name="Category",referencedColumnName="id_category_prod")
     */
    private $Category;

    /**

     * @ORM\Column(name="Promotion", type="boolean", nullable=true, options={"default":false})
     */
    protected $Promotion;


    /**

     *
     * @return mixed
     */
    public function getDateProduit()
    {
        return $this->DateProduit;
    }

    /**
     * @param mixed $DateProduit
     */
    public function setDateProduit($DateProduit)
    {
        $this->DateProduit = $DateProduit;
    }

    /**
     * @return mixed
     */
    public function getIdProduit()
    {
        return $this->IdProduit;
    }

    /**
     * @param mixed $IdProduit
     */
    public function setIdProduit($IdProduit)
    {
        $this->IdProduit = $IdProduit;
    }

    /**
     * @return mixed
     */
    public function getNameProduit()
    {
        return $this->NameProduit;
    }

    /**
     * @param mixed $NameProduit
     */
    public function setNameProduit($NameProduit)
    {
        $this->NameProduit = $NameProduit;
    }

    /**
     * @return mixed
     */
    public function getTypeProduit()
    {
        return $this->TypeProduit;
    }

    /**
     * @param mixed $TypeProduit
     */
    public function setTypeProduit($TypeProduit)
    {
        $this->TypeProduit = $TypeProduit;
    }

    /**
     * @return mixed
     */
    public function getQuantityProduit()
    {
        return $this->QuantityProduit;
    }

    /**
     * @param mixed $QuantityProduit
     */
    public function setQuantityProduit($QuantityProduit)
    {
        $this->QuantityProduit = $QuantityProduit;
    }

    /**
     * @return mixed
     */
    public function getPriceProduit()
    {
        return $this->PriceProduit;
    }

    /**
     * @param mixed $PriceProduit
     */
    public function setPriceProduit($PriceProduit)
    {
        $this->PriceProduit = $PriceProduit;
    }

    /**
     * @return mixed
     */
    public function getPictureProduit()
    {
        return $this->PictureProduit;
    }

    /**
     * @param mixed $PictureProduit
     */
    public function setPictureProduit($PictureProduit)
    {
        $this->PictureProduit = $PictureProduit;
    }

    /**
     * @return mixed
     */
    public function getDescriptionProduit()
    {
        return $this->DescriptionProduit;
    }

    /**
     * @param mixed $DescriptionProduit
     */
    public function setDescriptionProduit($DescriptionProduit)
    {
        $this->DescriptionProduit = $DescriptionProduit;
    }

    /**
     * @return mixed
     */
    public function getCategory()
    {
        return $this->Category;
    }

    /**
     * @param mixed $Category
     */
    public function setCategory($Category)
    {
        $this->Category = $Category;
    }

    /**
     * @return mixed
     */
    public function getPromotion()
    {
        return $this->Promotion;
    }

    /**
     * @param mixed $Promotion
     */
    public function setPromotion($Promotion)
    {
        $this->Promotion = $Promotion;
    }




}

ProduitBundle/Resources/views/Admin/afficheCategoryProduitAdmin.html.twig
{% extends 'base1.html.twig' %}

            {% block content %}



                <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Affichage Category Produit
                        </h3>

                        <div class="card-tools">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body table-responsive p-0">
                        <table class="table table-bordered table-striped">
                            <thead>
                            <tr>


                                <th>IdCategory</th>
                                <th>Libelle Produit</th>


                            </tr>
                            </thead>
                            <tbody>
                            {% for i in categorys %}
                                <tr>

                                    <td>{{ i.IdCategoryProd}}</td>
                                    <td>{{ i.LibelleProd}}</td>


                                    <td><a href="{{ path('Categprod_delete',{'IdCategoryProd':i.IdCategoryProd}) }}">
                                            <button type="button" class="btn btn-danger">
                                                <i class="fas fa-minus-circle"></i> Delete
                                            </button></a></td>


                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->




            {% endblock %}

ProduitBundle/Resources/views/Admin/afficheHistoryProduitAdmin.html.twig
{% extends 'base1.html.twig' %}

            {% block content %}
                <script>
                    function myFunction() {
                        var input, filter, table, tr, td, i, txtValue;
                        input = document.getElementById("recherche");
                        filter = input.value.toUpperCase();
                        table = document.getElementById("recherchetable");
                        tr = table.getElementsByTagName("tr");
                        for (i = 0; i < tr.length; i++) {
                            td = tr[i].getElementsByTagName("td")[1];
                            if (td) {
                                txtValue = td.textContent || td.innerText;
                                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                                    tr[i].style.display = "";
                                } else {
                                    tr[i].style.display = "none";
                                }
                            }
                        }
                    }
                </script>


                <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Affichage Produit
                        </h3>

                        <div class="card-tools">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="table_search"  id="recherche" onkeyup="myFunction()" class="form-control float-right" placeholder="Search">

                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body table-responsive p-0">
                        <table id="recherchetable"  class="table table-bordered table-striped">
                            <thead>
                            <tr>


                                <th>IdProduit</th>
                                <th>NameProduit</th>
                                <th>dateProduit </th>

                            </tr>
                            </thead>
                            <tbody>
                            {% for i in produits %}
                                <tr>

                                    <td>{{ i.IdProduit}}</td>
                                    <td>{{ i.nameProduit}}</td>
                                    <td>{{ i.dateproduit |date}}</td>

                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->




            {% endblock %}

ProduitBundle/Resources/views/Admin/afficheProduitAdmin.html.twig
{% extends 'base1.html.twig' %}

            {% block content %}
                <script>
                    function myFunction() {
                        var input, filter, table, tr, td, i, txtValue;
                        input = document.getElementById("recherche");
                        filter = input.value.toUpperCase();
                        table = document.getElementById("recherchetable");
                        tr = table.getElementsByTagName("tr");
                        for (i = 0; i < tr.length; i++) {
                            td = tr[i].getElementsByTagName("td")[0];
                            if (td) {
                                txtValue = td.textContent || td.innerText;
                                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                                    tr[i].style.display = "";
                                } else {
                                    tr[i].style.display = "none";
                                }
                            }
                        }
                    }
                </script>

                <script type="text/javascript" src="{{ asset('vendor/js/socialite.js') }}"></script>
                <script type="text/javascript" src="{{ asset('vendor/js/socialite.min.js') }}"></script>
                <!--...-->

                <ul class="social-buttons cf">
                    <li>
                        <a href="http://twitter.com/share" class="socialite twitter-share" data-text="Socialite.js" data-url="{{ app.request.getUri }}" data-count="vertical" rel="nofollow" target="_blank"><span class="vhidden">Share on Twitter</span></a>
                    </li>
                    <li>
                        <a href="https://plus.google.com/share?url={{ app.request.getUri }}" class="socialite googleplus-one" data-size="tall" data-href="{{ app.request.getUri }}" rel="nofollow" target="_blank"><span class="vhidden">Share on Google+</span></a>
                    </li>
                    <li>
                        <a href="http://www.facebook.com/sharer.php?u={{ app.request.getUri }} }}" class="socialite facebook-like" data-href="{{ app.request.getUri }}" data-send="false" data-layout="box_count" data-width="60" data-show-faces="false" rel="nofollow" target="_blank"><span class="vhidden">Share on Facebook</span></a>
                    </li>
                </ul>

                <!--...-->

                <script>
                    $(document).ready(function() {
                        Socialite.load();
                    });
                </script>


                <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Affichage Produit
                        </h3>

                        <div class="card-tools">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="table_search" id="recherche" onkeyup="myFunction()" class="form-control float-right" placeholder="Search">

                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body table-responsive p-0">
                        <table id="recherchetable" class="table table-bordered table-striped">
                            <thead>
                            <tr>



                                <th>NameProduit</th>
                                <th> Category</th>
                                <th>TypeProduit</th>
                                <th>quantityProduit</th>
                                <th>priceProduit.DT</th>
                                <th>Promotion.DT</th>
                                <th>pictureProduit </th>
                                <th>descriptionProduit </th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for i in produits %}
                                <tr>
                                    <td>{{ i.nameProduit}}</td>
                                    <td>{{i.Category}}</td>
                                    <td>{{ i.typeproduit}}</td>
                                    <td>{{ i.quantityproduit}}</td>
                                    <td>{{ i.priceproduit}}</td>

                                    {% if i.Promotion == true %}
                                       <td>{{ ((i.priceproduit)*3)/4}}</td>

                                    {% else %}
                                        <td>No promo</td>
                                    {% endif %}

                                    <td><img src="{{ asset('/Integration/public/uploads/')~i.pictureproduit}}" alt="message user image" class="direct-chat-img" ></td>
                                    <td>{{ i.descriptionproduit}}</td>
                                    <td><a href="{{ path('prod_update',{'IdProduit':i.IdProduit}) }}">
                                            <button type="button" class="btn btn-primary">
                                                <i class="fas fa-minus-circle"></i> update
                                            </button></a></td>
                                    <td><a href="{{ path('prod_delete',{'IdProduit':i.IdProduit}) }}">
                                            <button type="button" class="btn btn-primary">
                                                <i class="fas fa-minus-circle"></i> Supprimer
                                            </button></a></td>

                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->




            {% endblock %}

ProduitBundle/Resources/views/Admin/ajouterCategory.html.twig
{% extends 'base1.html.twig' %}

{% block content %}
    <h1>Ajouter une Category</h1>


    {{ form_start(f)}}
    {{ form_end(f)}}

{% endblock %}

ProduitBundle/Resources/views/Admin/ajouterProduit.html.twig
{% extends 'base1.html.twig' %}

{% block content %}
    <h1>Ajouter un Produit</h1>


    {{ form_start(f)}}
    {{ form_end(f)}}

{% endblock %}

ProduitBundle/Resources/views/Admin/homeAdmin.html.twig
{% extends 'base1.html.twig' %}

{% block content %}



{% endblock %}

ProduitBundle/Resources/views/Admin/modifierProduitAdmin.html.twig
{% extends 'base1.html.twig' %}
{% block content %}
    <h1>Modifier un Produit</h1>

    {{ form_start(f)}}
    {{ form_end(f)}}

{% endblock %}